org: kirthiss
app: testpyapi
service: aws-python-rest-api-project

frameworkVersion: ">=1.54.0 <3.0.0"

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: '20201221'

functions:
  totalgiving:
    handler: handler.totalgiving
    events:
      - http:
          path: /
          method: post

plugins:
  - serverless-python-requirements
