org: kirthiss
app: py-eventbridge

service: sulaba-api-deps
frameworkVersion: ">=1.54.0 <3.0.0"
custom:
  sulaba-region: uk-sulaba
provider:
  name: aws
  stage: dev
  region: us-east-1

resources:
  Resources:

    EventBus:
      Type: AWS::Events::EventBus
      Properties:
        Name: ${self:custom.sulaba-region}-${self:provider.stage}-bus
        
    SulabaQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.sulaba-region}-${self:provider.stage}-queue

    TotalGivingEventRule:
      Type: AWS::Events::Rule
      Properties:
        Name: TotalGiving
        Description: Sends totalgiving eventhooks to queue
        EventBusName: ${self:custom.sulaba-region}-${self:provider.stage}-bus
        EventPattern:
          source:
            - totalgiving
          detail:
            object:
              - donation
            event:
              - created
              - updated
        State: ENABLED
        # Targets:
          # - Arn: ${self:custom.sulaba-region}-${self:provider.stage}-queue
            # Id: TargetFunctionV1  

    NotifyWebhookEventFailedToValidate:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: ${self:custom.sulaba-region}-${self:provider.stage}-event-failed-to-validate
        TopicName: ${self:custom.sulaba-region}-${self:provider.stage}-event-failed-to-validate

    SulabaServerSecret:
      Type: AWS::SecretsManager::Secret
      Properties:
        Description: This is the data related to sulaba server access
        Name: ${file(./config.yml):odoo-server-secret}

  Outputs:
    SNSTargetForFailedEvents:
      Value:
        Ref: NotifyWebhookEventFailedToValidate
    SulabaServerSecretArn:
      Value:
        Ref: SulabaServerSecret
    EventBusArn:
      Value:
        Ref: EventBus
    SulabaQueueArn:
      Value:
        Ref: SulabaQueue
    TotalGivingEventRuleArn:
      Value:
        Ref: TotalGivingEventRule

    